export const MSAL_SIGNIN_PENDING = '@@msal/SIGNIN_PENDING';
export const MSAL_SIGNIN_SUCCESS = '@@msal/SIGNIN_SUCCESS';
export const MSAL_SIGNIN_FAILURE = '@@msal/SIGNIN_FAILURE';

export const MSAL_ACQUIRE_TOKEN_PENDING = '@@msal/ACQUIRE_TOKEN_PENDING';
export const MSAL_ACQUIRE_TOKEN_SUCCESS = '@@msal/ACQUIRE_TOKEN_SUCCESS';
export const MSAL_ACQUIRE_TOKEN_FAILURE = '@@msal/ACQUIRE_TOKEN_FAILURE';

export const MSAL_SIGNOUT = '@@msal/SIGNOUT';