export const SET_BUSINESSDATE_SELECTION = 'speedOfService.dashboard/SET_BUSINESSDATE_SELECTION';

export const FETCH_DASHBOARD_SUMMARIES = 'speedOfService.dashboard/FETCH_SUMMARIES';
export const FETCH_DASHBOARD_SUMMARIES_SUCCESS = 'speedOfService.dashboard/FETCH_SUMMARIES_SUCCESS';
export const FETCH_DASHBOARD_SUMMARIES_FAILURE = 'speedOfService.dashboard/FETCH_SUMMARIES_FAILURE';
export const FETCH_DASHBOARD_AVERAGES = 'speedOfService.dashboard/FETCH_AVERAGES';
export const FETCH_DASHBOARD_AVERAGES_SUCCESS = 'speedOfService.dashboard/FETCH_AVERAGES_SUCCESS';
export const FETCH_DASHBOARD_AVERAGES_FAILURE = 'speedOfService.dashboard/FETCH_AVERAGES_FAILURE';

export const FETCH_DAILYSUMMARIES = 'speedOfService/FETCH_DAILYSUMMARIES';
export const FETCH_DAILYSUMMARIES_SUCCESS = 'speedOfService/FETCH_DAILYSUMMARIES_SUCCESS';
export const FETCH_DAILYSUMMARIES_FAILURE = 'speedOfService/FETCH_DAILYSUMMARIES_FAILURE';
export const FETCH_DAILYAVERAGETIMES = 'speedOfService/FETCH_DAILYAVERAGETIMES';
export const FETCH_DAILYAVERAGETIMES_SUCCESS = 'speedOfService/FETCH_DAILYAVERAGETIMES_SUCCESS6';
export const FETCH_DAILYAVERAGETIMES_FAILURE = 'speedOfService/FETCH_DAILYAVERAGETIMES_FAILURE';