export const FETCH_DAILYSUMMARIES = 'speedOfService/FETCH_DAILYSUMMARIES';
export const FETCH_DAILYSUMMARIES_SUCCESS = 'speedOfService/FETCH_DAILYSUMMARIES_SUCCESS';
export const FETCH_DAILYSUMMARIES_FAILURE = 'speedOfService/FETCH_DAILYSUMMARIES_FAILURE';
export const FETCH_DAILYAVERAGETIMES = 'speedOfService/FETCH_DAILYAVERAGETIMES';
export const FETCH_DAILYAVERAGETIMES_SUCCESS = 'speedOfService/FETCH_DAILYAVERAGETIMES_SUCCESS6';
export const FETCH_DAILYAVERAGETIMES_FAILURE = 'speedOfService/FETCH_DAILYAVERAGETIMES_FAILURE';